# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'driverLicenseTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(975, 592)
        self.nextButton = QtWidgets.QPushButton(Form)
        self.nextButton.setGeometry(QtCore.QRect(600, 420, 211, 71))
        self.nextButton.setObjectName("nextButton")
        self.prevButton = QtWidgets.QPushButton(Form)
        self.prevButton.setGeometry(QtCore.QRect(160, 420, 211, 71))
        self.prevButton.setObjectName("prevButton")
        self.optionA = QtWidgets.QRadioButton(Form)
        self.optionA.setGeometry(QtCore.QRect(120, 330, 131, 41))
        self.optionA.setObjectName("optionA")
        self.optionB = QtWidgets.QRadioButton(Form)
        self.optionB.setGeometry(QtCore.QRect(340, 340, 95, 20))
        self.optionB.setObjectName("optionB")
        self.optionC = QtWidgets.QRadioButton(Form)
        self.optionC.setGeometry(QtCore.QRect(600, 340, 95, 20))
        self.optionC.setObjectName("optionC")
        self.optionD = QtWidgets.QRadioButton(Form)
        self.optionD.setGeometry(QtCore.QRect(790, 340, 95, 20))
        self.optionD.setObjectName("optionD")
        self.question = QtWidgets.QLabel(Form)
        self.question.setGeometry(QtCore.QRect(120, 40, 721, 241))
        self.question.setObjectName("question")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nextButton.setText(_translate("Form", "Next"))
        self.prevButton.setText(_translate("Form", "Previous"))
        self.optionA.setText(_translate("Form", "A"))
        self.optionB.setText(_translate("Form", "B"))
        self.optionC.setText(_translate("Form", "C"))
        self.optionD.setText(_translate("Form", "D"))
        self.question.setText(_translate("Form", "Question"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
