# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from quizWin import *

class Ui_homeWin(object):

    def setupUi(self, homeWin):
        homeWin.setObjectName("homeWin")
        homeWin.resize(544, 543)
        self.centralwidget = QtWidgets.QWidget(homeWin)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(104, 180, 101, 20))
        self.label.setObjectName("label")
        self.enterName = QtWidgets.QLineEdit(self.centralwidget)
        self.enterName.setGeometry(QtCore.QRect(180, 180, 201, 22))
        self.enterName.setObjectName("enterName")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(230, 240, 101, 31))
        self.startButton.setObjectName("startButton")
        homeWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(homeWin)
        self.statusbar.setObjectName("statusbar")
        homeWin.setStatusBar(self.statusbar)

        self.retranslateUi(homeWin)
        QtCore.QMetaObject.connectSlotsByName(homeWin)

    def retranslateUi(self, homeWin):
        _translate = QtCore.QCoreApplication.translate
        homeWin.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter name: "))
        self.startButton.setText(_translate("MainWindow", "Start"))

        # Click Start button to start quiz
        self.startButton.clicked.connect(self.startQuiz)
        self.startButton.clicked.connect(homeWin.close)

    def startQuiz(self):
        self.queswin = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.queswin)
        self.queswin.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homeWin = QtWidgets.QMainWindow()
    ui = Ui_homeWin()
    ui.setupUi(homeWin)
    homeWin.show()
    sys.exit(app.exec_())
